""" XDG compliance
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

""" Sugar
" Line numbers
set number
" Syntax highlighting
syntax on
" Blinking cursor in INSERT
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
" Mouse support
set mouse=a

""" Plugins
call plug#begin($XDG_CONFIG_HOME.'/vim/plugged')

" Lightline
Plug 'itchyny/lightline.vim'
set laststatus=2
set noshowmode

call plug#end()
