#! /bin/sh

# autostarts
declare -a commands=(
    "sxhkd"
)
for command in "${commands[@]}"; do
    pgrep -x $command || $command &
done

# fuzzy focus
bspc config focus_follows_pointer true

# borders and gaps
bspc config border_width 2
bspc config window_gap   4

# desktops
bspc monitor -d {I,II,III,IV,V,VI,VII,VIII,IX,X}

# floating rules
bspc rule -a "Wrapper-2.0" state=pseudo_tiled
bspc rule -a "Xfce4-appfinder" state=floating
bspc rule -a "Xfce4-panel" state=floating

# desktop rules
bspc rule -a "org.mozilla.firefox" desktop=^1
